[workspace]
members = [
    "harness",
]
resolver = "2"

[workspace.dependencies]
bincode = "1.3.3"
solana-bpf-loader-program = "1.18.14"
solana-program-runtime = "1.18.14"
solana-system-program = "1.18.14"
solana-sdk = "1.18.14"
